import { lazy } from 'react'

export const toolGroups = [
  {
    id: 'encoding',
    name: '加密 / 编码',
    tools: [
      { id: 'md5-hash', name: 'MD5 生成' },
      { id: 'sha-hash', name: 'SHA 系列' },
      { id: 'base64-tool', name: 'Base64 编码/解码' },
      { id: 'url-codec', name: 'URL 编码/解码' },
      { id: 'html-entities', name: 'HTML 实体编码/解码' },
      { id: 'jwt-decode', name: 'JWT 解码' },
    ],
  },
  {
    id: 'formatting',
    name: '数据格式化 / 转换',
    tools: [
      { id: 'json-tool', name: 'JSON 格式化/压缩/校验' },
      { id: 'xml-tool', name: 'XML 格式化/压缩' },
      { id: 'yaml-json', name: 'YAML ↔ JSON' },
      { id: 'toml-json', name: 'TOML ↔ JSON' },
      { id: 'csv-json', name: 'CSV ↔ JSON' },
      { id: 'json-sql', name: 'JSON ↔ SQL 转换' },
      { id: 'code-beautify', name: 'HTML/JS/CSS 美化/压缩' },
      { id: 'sql-format', name: 'SQL 格式化' },
    ],
  },
  {
    id: 'network',
    name: '网络 / 调试工具',
    tools: [
      { id: 'url-params', name: 'URL 参数提取' },
      { id: 'cookie-format', name: 'Cookie 格式化' },
      { id: 'ua-parse', name: 'User-Agent 解析' },
      { id: 'ip-convert', name: 'IP 地址转换' },
      { id: 'port-scan', name: '端口扫描示例' },
      { id: 'http-header', name: 'HTTP Header 格式化' },
      { id: 'curl-requests', name: 'cURL ↔ requests 转换' },
    ],
  },
  {
    id: 'text',
    name: '文本处理工具',
    tools: [
      { id: 'text-case', name: '大小写转换' },
      { id: 'text-clean', name: '文本去重 / 排序 / 去空行' },
      { id: 'text-stats', name: '文本统计' },
      { id: 'text-diff', name: '文本差异对比' },
      { id: 'password-gen', name: '随机密码生成器' },
      { id: 'lorem-ipsum', name: '占位符文本生成' },
      { id: 'markdown-html', name: 'Markdown ↔ HTML 转换' },
    ],
  },
  {
    id: 'time',
    name: '时间 / 日期工具',
    tools: [
      { id: 'unix-time', name: 'Unix 时间戳 ↔ 日期时间' },
      { id: 'countdown-timer', name: '倒计时/定时器' },
      { id: 'cron-parser', name: 'Cron 表达式解析' },
    ],
  },
  {
    id: 'dev',
    name: '前端 / 开发辅助',
    tools: [
      { id: 'regex-tester', name: '正则表达式测试' },
      { id: 'base-convert', name: '进制转换' },
      { id: 'color-convert', name: 'RGB ↔ HEX ↔ HSL' },
      { id: 'color-picker', name: '取色器工具' },
      { id: 'qr-tool', name: '二维码生成 / 解码' },
      { id: 'barcode-gen', name: '条形码生成' },
      { id: 'uuid-gen', name: 'UUID 生成' },
    ],
  },
  {
    id: 'media',
    name: '图像 / 多媒体',
    tools: [
      { id: 'image-base64', name: '图片转 Base64' },
      { id: 'base64-image', name: 'Base64 转图片' },
      { id: 'image-compress', name: '图片压缩' },
      { id: 'favicon-gen', name: '图标生成（Favicon 预览）' },
      { id: 'audio-analyzer', name: '音频频率分析' },
    ],
  },
  {
    id: 'misc',
    name: '办公 / 杂项工具',
    tools: [
      { id: 'unit-convert', name: '单位换算器' },
      { id: 'currency-convert', name: '货币汇率换算' },
      { id: 'email-signature', name: '邮箱签名生成' },
      { id: 'vcard-qr', name: '二维码名片生成' },
      { id: 'mermaid-diagram', name: '思维导图/流程图' },
      { id: 'random-tool', name: '随机数/骰子/抽签' },
      { id: 'calendar-notes', name: '日历/记事本' },
    ],
  },
]

export const toolComponents = {
  'md5-hash': lazy(() => import('./encoding/MD5Generator.jsx')),
  'sha-hash': lazy(() => import('./encoding/SHATool.jsx')),
  'base64-tool': lazy(() => import('./encoding/Base64Tool.jsx')),
  'url-codec': lazy(() => import('./encoding/UrlCodec.jsx')),
  'html-entities': lazy(() => import('./encoding/HtmlEntityTool.jsx')),
  'jwt-decode': lazy(() => import('./encoding/JwtDecoder.jsx')),

  'json-tool': lazy(() => import('./formatting/JsonTool.jsx')),
  'xml-tool': lazy(() => import('./formatting/XmlTool.jsx')),
  'yaml-json': lazy(() => import('./formatting/YamlJsonTool.jsx')),
  'toml-json': lazy(() => import('./formatting/TomlJsonTool.jsx')),
  'csv-json': lazy(() => import('./formatting/CsvJsonTool.jsx')),
  'json-sql': lazy(() => import('./formatting/JsonSqlTool.jsx')),
  'code-beautify': lazy(() => import('./formatting/CodeBeautify.jsx')),
  'sql-format': lazy(() => import('./formatting/SqlFormatter.jsx')),

  'url-params': lazy(() => import('./network/UrlParamExtractor.jsx')),
  'cookie-format': lazy(() => import('./network/CookieFormatter.jsx')),
  'ua-parse': lazy(() => import('./network/UserAgentParser.jsx')),
  'ip-convert': lazy(() => import('./network/IpConverter.jsx')),
  'port-scan': lazy(() => import('./network/PortScanner.jsx')),
  'http-header': lazy(() => import('./network/HttpHeaderFormatter.jsx')),
  'curl-requests': lazy(() => import('./network/CurlRequestsConverter.jsx')),

  'text-case': lazy(() => import('./text/TextCaseTool.jsx')),
  'text-clean': lazy(() => import('./text/TextCleaner.jsx')),
  'text-stats': lazy(() => import('./text/TextStatistics.jsx')),
  'text-diff': lazy(() => import('./text/TextDiffViewer.jsx')),
  'password-gen': lazy(() => import('./text/PasswordGenerator.jsx')),
  'lorem-ipsum': lazy(() => import('./text/LoremIpsum.jsx')),
  'markdown-html': lazy(() => import('./text/MarkdownHtmlTool.jsx')),

  'unix-time': lazy(() => import('./time/UnixTimeConverter.jsx')),
  'countdown-timer': lazy(() => import('./time/CountdownTimer.jsx')),
  'cron-parser': lazy(() => import('./time/CronParser.jsx')),

  'regex-tester': lazy(() => import('./dev/RegexTester.jsx')),
  'base-convert': lazy(() => import('./dev/BaseConverter.jsx')),
  'color-convert': lazy(() => import('./dev/ColorConverter.jsx')),
  'color-picker': lazy(() => import('./dev/ColorPicker.jsx')),
  'qr-tool': lazy(() => import('./dev/QrTool.jsx')),
  'barcode-gen': lazy(() => import('./dev/BarcodeGenerator.jsx')),
  'uuid-gen': lazy(() => import('./dev/UuidGenerator.jsx')),

  'image-base64': lazy(() => import('./media/ImageToBase64.jsx')),
  'base64-image': lazy(() => import('./media/Base64ToImage.jsx')),
  'image-compress': lazy(() => import('./media/ImageCompressor.jsx')),
  'favicon-gen': lazy(() => import('./media/FaviconGenerator.jsx')),
  'audio-analyzer': lazy(() => import('./media/AudioAnalyzer.jsx')),

  'unit-convert': lazy(() => import('./misc/UnitConverter.jsx')),
  'currency-convert': lazy(() => import('./misc/CurrencyConverter.jsx')),
  'email-signature': lazy(() => import('./misc/EmailSignatureGenerator.jsx')),
  'vcard-qr': lazy(() => import('./misc/VCardGenerator.jsx')),
  'mermaid-diagram': lazy(() => import('./misc/MermaidDiagram.jsx')),
  'random-tool': lazy(() => import('./misc/RandomTool.jsx')),
  'calendar-notes': lazy(() => import('./misc/CalendarNotes.jsx')),
}
